shared:
  project_dir: "./tutorial_project"
  tomo0_files: 
    - "./tutorial_data/tomo_even_frames.rec"
  tomo1_files: 
    - "./tutorial_data/tomo_odd_frames.rec"
  subtomo_size: 96
  mw_angle: 50
  num_workers: 10
  gpu: [0, 1]
  distributed_backend: "gloo"
  seed: 42

prepare_data:
  mask_files:
    - "./tutorial_data/mask.mrc"
  min_nonzero_mask_fraction_in_subtomo: 0.3
  subtomo_extraction_strides: [64, 80, 80] 
  val_fraction: 0.2

fit_model:
    unet_params_dict:
      chans: 64
      num_downsample_layers: 3
      drop_prob: 0.0
    adam_params_dict: 
      lr: 0.0004
    num_epochs: 1000
    batch_size: 1
    update_subtomo_missing_wedges_every_n_epochs: 10
    check_val_every_n_epochs: 10
    save_n_models_with_lowest_val_loss: 5
    save_n_models_with_lowest_fitting_loss: 5
    save_model_every_n_epochs: 50
    logger: "csv"


refine_tomogram:
    model_checkpoint_file: "./tutorial_data/fitted_model.ckpt"
    subtomo_overlap: 32
    batch_size: 10